services:
  frontend:
    env_file:
      - .env
    build:
      context: ./frontend
      dockerfile: ./docker/prod/Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=/api
    environment:
      - NEXT_PUBLIC_API_BASE_URL=/api
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    networks:
      - app_network
    # Not exposing frontend port directly in production

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      dockerfile: ./docker/prod/Dockerfile
    entrypoint: ["/entrypoint.sh"]
    environment:
      - DATABASE_URL=postgresql://user:password@db/osm_tracker_db
      - DEBUG=False
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app_network
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: osm_tracker_db
    networks:
      - app_network
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d osm_tracker_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge

